# Generated by Django 4.1.7 on 2023-04-11 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0002_suppliments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
