# Generated by Django 4.1.7 on 2023-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0003_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='supplements',
            field=models.ManyToManyField(to='livestockapp.suppliments'),
        ),
    ]
