# Generated by Django 4.1.7 on 2023-04-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0004_tempcart_supplements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='amount',
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='Nairobi', max_length=400),
        ),
    ]
