# Generated by Django 4.1.7 on 2023-04-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0005_remove_inventory_amount_inventory_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='category',
            field=models.CharField(default='Suppliment', max_length=400),
        ),
    ]
