# Generated by Django 4.1.7 on 2023-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0006_tempcart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcart',
            name='category',
        ),
        migrations.AddField(
            model_name='suppliments',
            name='category',
            field=models.CharField(default='Suppliment', max_length=400),
        ),
    ]
