# Generated by Django 4.1.7 on 2023-04-15 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livestockapp', '0008_suppliments_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplimentorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('totalprice', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suppliments', models.ManyToManyField(to='livestockapp.suppliments')),
            ],
        ),
    ]
