# Generated by Django 4.1.7 on 2023-04-15 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestockapp', '0009_supplimentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcart',
            name='supplements',
        ),
        migrations.DeleteModel(
            name='supplimentorder',
        ),
        migrations.DeleteModel(
            name='suppliments',
        ),
    ]
